### ISSUE TITLE
Customizable message

### ISSUE THREAD

**Issue by comfysquirrel** [PaddyWagon/ActionBar-PlotSquared#2]
I'd like to be able to change the color of the message. I suppose it would make sense to make the whole message customizable?

**Comment by pshadoyan** [comment]
I'll add this in the next update, it'll be done in a bit. Great suggestion!

**Comment by pshadoyan** [comment]
Here's the update https://github.com/PaddyWagon/ActionBar-PlotSquared/releases/tag/1.2
Let me know if there's anything else you'd like me to add!

Regards, 
Paddy

@jonthesquirrel

**Comment by comfysquirrel** [comment]
Works perfectly! :D
